### ISSUE TITLE
Compensation

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#2683]
## Feature

We need a way for workflows to compensate for when a workflow faults so that previously executed activities can e.g. cleanup.
When a workflow compensates, its final status will be `Cancelled` rather than `Faulted`.

The below description is a revised version based on the [approach taken by Windows Workflow Foundation](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/dd489432(v=vs.100)?redirectedfrom=MSDN), which I think is a more flexible approach compared to the previous description.

> Use the Revision feature to read the previous description:
> ![image](https://user-images.githubusercontent.com/938393/163358498-cf1284be-89b2-4cd3-9035-cebf0bc3682c.png)

### Compensable Activity

The Compensable Activity has 5 outcomes:

- Body
- Compensate
- Cancel
- Confirm
- Done

#### Body

The **Body** outcome lets the user specify what work to be done within the scope of the compensable activity.

#### Done

Once the **Body** branch completes, the **Done** outcome is scheduled.

#### Compensate

If any activity causes an unhandled exception in the **Done** branch, the **Compensate** outcome of the compensable activity will be scheduled, allowing the workflow to undo actions as necessary.

#### Cancel

If an activity within the **Body** branch faults, the **Cancel** outcome is scheduled. 

#### Confirm

For some scenarios, compensable activities should no longer allow to be compensated anymore.
To control this, the user should be able to explicitly **confirm** a compensable activity. When this happens, the **Confirm** outcome will be scheduled, allowing the user to do any work that finalizes some state.

### Compensate Activity

Whenever an activity faults, any upper Compensable activity in its inbound branch will have its Compensate outcome scheduled for execution.

However, this is not always enough. Some activities can have an e.g. "Error" outcome. For example, the `SendHttpRequest` activity let's the user handle HTTP 500 status codes as an outcome. It is reasonable to allow the user to undo work that was done earlier in the workflow.

To allow for this, the user can add a `Compensate` activity and specify the name of the Compensable activity.

### Confirm Activity

To confirm a compensable activity, the user can use the `Confirm` activity by specifying the name of the compensable activity.
This will result in the **Confirm** outcome of the compensable activity to be scheduled for execution.

Confirmed compensable activities can no longer compensate. Trying to do so will cause an exception.

### Task list

To implement this feature, we need to do the following:

- [x] Create the `Compensable` activity.
- [x] Create the `Fault` activity that allows users to explicitly fault a workflow
- [x] Create the `Compensate` activity that allows users to explicitly compensate a specific compensable activity.
- [ ] Create the `Confirm` activity that allows users to explicitly confirm a specific compensable activity.

**Comment by tomy2105** [comment]
Yes!!!! Have a need myself for something like this but never got around to word it here!

**Comment by mohdali** [comment]
Totally agree.

Probably one idea is to define a fault handling workflow that can take care of sending notifications, undoing actions, rolling back transactions, etc.

Maybe each flow should have an exeution mode and an optional fault handling mode, both configurable from the designer.

**Comment by jamshally** [comment]
Agreed - compensating actions would be great - and are very closely aligned with the Saga pattern. In case useful as a reference, MassTransit has a decent implemententation [Sagas ](https://masstransit-project.com/usage/sagas/) and [Compensating Events](https://masstransit-project.com/advanced/courier/activities.html#compensating-an-activity)

**Comment by sfmskywalker** [comment]
> Totally agree.
> 
> Probably one idea is to define a fault handling workflow that can take care of sending notifications, undoing actions, rolling back transactions, etc.
> 
> Maybe each flow should have an exeution mode and an optional fault handling mode, both configurable from the designer.

Exactly. With the new `Compensable` activity, you'll be able to execute arbitrary "cleanup" logic and send notifications etc. It's close to what you describe as "fault handling mode" - just implemented as an activity.

**Comment by rajasekarshanmugam** [comment]
Are there any doc references on the usage? Saw the test samples, but could not find how to sequence or nest compensations.

**Comment by Nhollas** [comment]
@sfmskywalker Hey bro, I've just cloned the example project here: https://github.com/elsa-workflows/elsa-core/tree/master/src/samples/console/Elsa.Samples.CompensationConsole

When faults occur in the done path they are not correctly routing to the compensate path.
![image](https://user-images.githubusercontent.com/54915148/229556165-83d68a94-d5ca-486a-83a0-bbe3c30a6b96.png)

Any ideas as to why this is happening?

**Comment by sfmskywalker** [comment]
Hi @Nhollas , that is by design. Only activities that fault in the Body branch will trigger the Compensate branch. This allows you to model processes to continue with logic where compensation would no longer make sense after a certain stage has been reached. For example, if your process included a flight reservation, payment and the actual flight, compensation would nog longer be allowed after the flight finishes. You can of course add subsequent Compensable activities.

**Comment by Nhollas** [comment]
Hi @sfmskywalker, thanks for getting back.

I see, I was getting confused as following this:

> Body
> The Body outcome lets the user specify what work to be done within the scope of the compensable activity.
> 
> Done
> Once the Body branch completes, the Done outcome is scheduled.
> 
> Compensate
> If any activity causes an unhandled exception in the Done branch, the Compensate outcome of the compensable activity will be scheduled, allowing the workflow to undo actions as necessary.
> 
> Cancel
> If an activity within the Body branch faults, the Cancel outcome is scheduled.
> 
> Confirm
> For some scenarios, compensable activities should no longer allow to be compensated anymore.
> To control this, the user should be able to explicitly confirm a compensable activity. When this happens, the Confirm outcome will be scheduled, allowing the user to do any work that finalizes some state.
> 

With your comment in mind, what else from above is incorrect? 👍  :)

**Comment by sfmskywalker** [comment]
Well, consider me schooled. Please forget my previous comment 😅 
In which case, the Done branch not triggering the Compensate branch would be a bug.

**Comment by Nhollas** [comment]
Interesting... is a small fix? I've never contributed to an open-source project before but with some guidance I can open a PR. 👍

**Comment by sfmskywalker** [comment]
It might be an easy fix, but hard to say without digging into it. It would be fantastic if you want to give it a try. I'll be here to help you in any way I can 👍🏻

**Comment by BrianCham** [comment]
> @Nhollas @sfmskywalker
> 
> I've been taking a look at this and can confirm this is working on version 2.10.2.2. I cloned the repo and looked at changes from 2.10.2.2 -> 2.11.0.
> 
> It looks like the break; on line 338 on the WorkflowRunner.cs is breaking this. https://github.com/elsa-workflows/elsa-core/blob/master/src/core/Elsa.Core/Services/Workflows/WorkflowRunner.cs#L338
> 
> Similar to @Nhollas, I have never contributed before. I'm not sure if removing the break; on line 338 will break other functionality.

Yes, I found that caused Compensable activity malfunctional. Actually, in 2.10.2.2,  a Fault activity in Body branch wouldn't not trigger any Compensation actitivity, it worked only in Done branch.
