### ISSUE TITLE
Add Retry + Bulk Retry option to UI

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#2762]
## Feature

As a user, I should be able to retry faulted workflows from the dashboard:

- Via the context menu
- Via the bulk action dropdown

The necessary API endpoints already exist [here](https://github.com/elsa-workflows/elsa-core/blob/master/src/server/Elsa.Server.Api/Endpoints/WorkflowInstances/BulkRetry.cs) and [here](https://github.com/elsa-workflows/elsa-core/blob/master/src/server/Elsa.Server.Api/Endpoints/WorkflowInstances/Retry.cs).

### Tasks

- [x] Implement Bulk Retry
- [x] Implement Retry via context menu
- [x] For either action, display a prompt: "Are you sure you want to retry the selected workflows?" / "Are you sure you want to retry this workflow?"
