### ISSUE TITLE
Designer & Dashboard Task List

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#721]
This issue keeps track of a list of tasks and bugs to be fixed before 2.0 can become RC.

### Workflow Editor
- [x] When clicking the Publish button, we need to see a visual indication that the workflow was published successfully.
- [x] We need a visual indicator that displays when the workflow is being saved, and when it completed successfully or unsuccessfully. When unsuccessful, we need to be able to see the error.
- [x] Add "Unpublish" item to Publish button. Clicking this should set the Published flag to false so that no new workflow instances will be created while the workflow is unpublished. Existing workflow instances will continue to execute.
- [x] The designer allows for new connections to be created by dragging from an activity's outcome buttons to another activity, but the connection is not persisted.
- [x] We need to be able to delete connections.
- [x] We need to be able to connect already connected activities to outcomes of other activities.
- [x] The Monaco Editor currently requires to be included separately from the index page due to the initialization needed for its workers. Right now these scripts are included from unpkg.com. At the very least, we should either mark Monaco as a peer dependency, and see if we can package the worker init code so that the developer doesn't have to copy & paste this in their projects using the designer.
- [x] Provide proper icons for each activity.
- [x] Add Persistence Behavior settings to Workflow Settings dialog.
- [x] Add common activity tab view (Name, Display Name, Description)
- [x] Make Import/Export functional.
- [x] Configure activities with proper input editors (While, ForEach, For, ParallelForEach, RunWorkflow, Finish).
- [x] Build input controls for Switch activity.
- [x] Perf: Designer becomes "slow" as more activities get added.

### Workflow Viewer
- [x] We need a workflow viewer component to view workflow instances.
- [x] Each executed activity should have a list of small numbered bulbs to indicate in which order they executed. Hovering over a given bulb should show a tooltip of some kind to display information like executed at, the time it took to execute, and any faults that may have occurred.
- [x] Execution log view.
- [ ] Optional for now, but would be nice to have a "replay" button that animates workflow execution by highlighting one activity at a time. Perhaps with a console window that shows its current input and output.
- [x] Implement workflow blueprint viewer (from workflow registry) for coded workflows. For designed / data workflows, use workflow definition editor component.

### Dashboard
- [x] Workflow Blueprints list view: show accurate number of workflow instances in INSTANCES column.
- [x] Workflow Instances list view: sorting is lost when paging.
- [ ] Workflow Instances list view: auto-refresh view or add refresh button for manual refresh.

**Comment by tomy2105** [comment]
I wish, more important, undo/redo (https://github.com/elsa-workflows/elsa-core/issues/794) was on the list as well as, a bit less important,  copy/paste (https://github.com/elsa-workflows/elsa-core/issues/792).

**Comment by sfmskywalker** [comment]
I understand, and it is an important feature. But not IMHO nearly important enough when compared to usability issues that are problematic. I see these priority labels as relative to one another, and they may change over time as we re-prioritize. For now, it is low on the list. Doesn't mean nobody can work on them of course.

**Comment by tomy2105** [comment]
Yes, I agree that those two are lower priority than https://github.com/elsa-workflows/elsa-core/issues/781 or https://github.com/elsa-workflows/elsa-core/issues/780 :).

**Comment by sfmskywalker** [comment]
Skipping the following two items for now:

- [ ] Optional for now, but would be nice to have a "replay" button that animates workflow execution by highlighting one activity at a time. Perhaps with a console window that shows its current input and output.
- [ ] Workflow Instances list view: auto-refresh view or add refresh button for manual refresh.

They are both nice to have, but not important enough to block the RC release.
